### ISSUE TITLE
Typescript Typings

### ISSUE THREAD

**Issue by korve** [oransel/node-talib#47]
Hey, i've made a small script to generate typings for typescript. I'm just not too deep into talib to confirm they are correct. Can someone look over it? Would appreciate it.

Repo is here: https://github.com/korve/talib-typings
Generated .d.ts is here: https://github.com/korve/talib-typings/blob/master/index.d.ts

**Comment by Unibozu** [comment]
Hey Korve,
not a maintainer but I've also started working on typing on a side project. Typescript is rather new to me so don't hesitate to let me know if something feels wrong in my comments:

* type `real` are typed as `number[]`
* it may be interesting to provide a strict list of parameters for each function instead of inheriting from a common interface which some functions don't need (for instance MACD only needs `inReal` `startIdx` `endIdx`). By not including unused parameters this may reduce the need to check on further documentation/examples as the input/output of each individual function is clear.
